import React, { createContext, useState, useEffect } from "react";

export const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(
    localStorage.getItem("appLang") || "en",
  );

  useEffect(() => {
    localStorage.setItem("appLang", language);
  }, [language]);

  // VIP Dictionary (100% COMPLETE APP WITH NEW TERMS)
  const translations = {
    en: {
      // Menu & General
      Dashboard: "Dashboard",
      Vehicles: "Vehicles",
      Routes: "Routes",
      Shops: "Shops",
      "Daily Collection": "Daily Collection",
      "Factory Weight": "Factory Weight",
      "Shop Ledger": "Shop Ledger",
      "Route Ledger Summary": "Route Ledger Summary",
      "Monthly Reports": "Monthly Reports",
      Users: "Users",
      Settings: "Settings",
      Logout: "Logout",
      "Keep Environment Clean": "Keep Environment Clean For Better Tomorrow",
      "Management System": "Management System",
      Cancel: "Cancel",
      Save: "Save",
      "Saving...": "Saving...",
      Status: "Status",
      Active: "Active",
      Inactive: "Inactive",
      Actions: "Actions",
      Edit: "Edit",
      Delete: "Delete",
      "Yes, Delete": "Yes, Delete",
      Month: "Month",
      Year: "Year",
      Date: "Date",
      Action: "Action",
      Name: "Name",

      // Dashboard
      "Welcome to Waste Management System":
        "Welcome to Waste Management System",
      "Here is what's happening today, ": "Here is what's happening today, ",
      "Filter Overview": "Filter Overview",
      "Select Date": "Select Date",
      "Select Route": "Select Route",
      "All Routes (Overall)": "All Routes (Overall)",
      "Collection & Financials": "Collection & Financials",
      "Total Shop Weight": "Total Shop Weight",
      "Total Factory Weight": "Total Factory Weight",
      "Total Difference": "Total Difference",
      "Infrastructure Overview": "Infrastructure Overview",
      "Active Vehicles": "Active Vehicles",
      "Active Routes": "Active Routes",
      "Registered Shops": "Registered Shops",

      // Daily Collection & Shop Ledger
      "Daily Shop Collection / Weight Entry":
        "Daily Shop Collection / Weight Entry",
      "Record daily poultry waste collection from shops":
        "Record daily poultry waste collection from shops",
      "-- Select Route --": "-- Select Route --",
      "Assigned Vehicle": "Assigned Vehicle",
      "No Vehicle!": "No Vehicle!",
      "Loading shops...": "Loading shops...",
      "No shops are assigned to this route. Please add shops first.":
        "No shops are assigned to this route. Please add shops first.",
      "Shop Name": "Shop Name",
      "Rate / KG": "Rate / KG",
      "Weight Input": "Weight Input",
      "Total Amount (Rs)": "Total Amount (Rs)",
      "Calculated:": "Calculated:",
      "Route Total:": "Route Total:",
      "Rate:": "Rate:",
      "Enter Weight": "Enter Weight",
      "Total Amount:": "Total Amount:",
      "Route Total Weight:": "Route Total Weight:",
      "Total Payable:": "Total Payable:",
      "Saving Collection...": "Saving Collection...",
      "Save Daily Collection": "Save Daily Collection",
      "Shop Ledger & Payments": "Shop Ledger & Payments",
      "Save PDF": "Save PDF",
      "Add Payment": "Add Payment",
      "Select Shop": "Select Shop",
      "-- Select Shop --": "-- Select Shop --",
      "Edit Payment": "Edit Payment",
      "Record New Payment": "Record New Payment",
      "Amount (Rs.) *": "Amount (Rs.) *",
      "Type *": "Type *",
      "Debit (Paid to Shop)": "Debit (Paid to Shop)",
      "Credit (Advance / Adjust)": "Credit (Advance / Adjust)",
      Method: "Method",
      Cash: "Cash",
      Check: "Check",
      "Bank Transfer": "Bank Transfer",
      Other: "Other",
      "Notes / Check No.": "Notes / Check No.",
      "Update Payment": "Update Payment",
      "Save Payment": "Save Payment",
      "Total Collected": "Total Collected",
      "Total Payable (Credit)": "Total Payable (Credit)",
      "Total Paid (Debit)": "Total Paid (Debit)",
      "Remaining Balance": "Remaining Balance",
      Description: "Description",
      "Weight / Rate": "Weight / Rate",
      "Debit (Paid)": "Debit (Paid)",
      "Credit (Payable)": "Credit (Payable)",
      Balance: "Balance",
      "No transactions found.": "No transactions found.",
      "Waste Collection": "Waste Collection",
      Payment: "Payment",
      "Note:": "Note:",
      "Weight (KG)": "Weight (KG)",
      "Enter Weight (KG)": "Enter Weight (KG)",

      // Factory Weight
      "Factory Weight & Reports": "Factory Weight & Reports",
      "Record New Factory Weight": "Record New Factory Weight",
      "No collection found for this date.":
        "No collection found for this date.",
      "Enter Factory Weight *": "Enter Factory Weight *",
      Difference: "Difference",
      "Notes (Optional)": "Notes (Optional)",
      "Save Weight": "Save Weight",
      "Monthly Factory Report": "Monthly Factory Report",
      "Excel File": "Excel File",
      Route: "Route",
      "Shop Wgt": "Shop Wgt",
      "Factory Wgt": "Factory Wgt",
      Diff: "Diff",
      "Status / Notes": "Status / Notes",
      "No factory records found for this month.":
        "No factory records found for this month.",
      "Edit Factory Weight": "Edit Factory Weight",
      "Shop Weight:": "Shop Weight:",
      "New Factory Weight (KG)": "New Factory Weight (KG)",
      Notes: "Notes",
      "Update Record": "Update Record",
      Extra: "Extra",
      Shortage: "Shortage",
      Balanced: "Balanced",

      // Shops & Routes
      "Shops Management": "Shops Management",
      "Add Shop": "Add Shop",
      "Edit Shop": "Edit Shop",
      "Add New Shop": "Add New Shop",
      "Shop Name *": "Shop Name *",
      "Owner Name *": "Owner Name *",
      "Contact (Optional)": "Contact (Optional)",
      "Assign Route *": "Assign Route *",
      "Rate per KG (Rs.) *": "Rate per KG (Rs.) *",
      "Save Shop": "Save Shop",
      "Owner & Contact": "Owner & Contact",
      "Assigned Route": "Assigned Route",
      "Rate/KG": "Rate/KG",
      "No shops found. Please add a new shop.":
        "No shops found. Please add a new shop.",
      "Delete Shop?": "Delete Shop?",
      "Are you sure you want to delete this shop? This action cannot be undone.":
        "Are you sure you want to delete this shop? This action cannot be undone.",
      "Routes Management": "Routes Management",
      "Add Route": "Add Route",
      "Edit Route": "Edit Route",
      "Add New Route": "Add New Route",
      "Route Name *": "Route Name *",
      "Assign Vehicle": "Assign Vehicle",
      "-- Select --": "-- Select --",
      "Route Name": "Route Name",
      Vehicle: "Vehicle",
      Driver: "Driver",
      "Not Assigned": "Not Assigned",
      "Delete Route?": "Delete Route?",
      "Serial Number": "Serial Number",
      "Sr. No": "Sr. No",
      "All Routes": "All Routes",
      "Serial updated!": "Serial updated!",
      "Failed to update serial": "Failed to update serial",

      // Vehicles
      "Vehicles Management": "Vehicles Management",
      "Manage all your transport vehicles":
        "Manage all your transport vehicles",
      "Add Vehicle": "Add Vehicle",
      "Edit Vehicle": "Edit Vehicle",
      "Add New Vehicle": "Add New Vehicle",
      "Vehicle Number *": "Vehicle Number *",
      "Vehicle Name/Type": "Vehicle Name/Type",
      "Driver Name *": "Driver Name *",
      "Driver Contact *": "Driver Contact *",
      "Under Maintenance": "Under Maintenance",
      "Update Vehicle": "Update Vehicle",
      "Save Vehicle": "Save Vehicle",
      "Vehicle No.": "Vehicle No.",
      "Name/Type": "Name/Type",
      Contact: "Contact",
      "Delete Vehicle?": "Delete Vehicle?",

      // Monthly Reports & Route Ledger
      "Monthly Business Report": "Monthly Business Report",
      "Generate, view, and export overall business summaries":
        "Generate, view, and export overall business summaries",
      "Generating...": "Generating...",
      "Generate Report": "Generate Report",
      "For ": "For ",
      Print: "Print",
      PDF: "PDF",
      Excel: "Excel",
      "Total Routes": "Total Routes",
      "Total Vehicles": "Total Vehicles",
      "Total Shops": "Total Shops",
      "Total Payable Amount": "Total Payable Amount",
      "Total Shop Weight (KG)": "Total Shop Weight (KG)",
      "Total Factory Weight (KG)": "Total Factory Weight (KG)",
      "Total Difference (KG)": "Total Difference (KG)",
      "Total Payable Amount (Rs.)": "Total Payable Amount (Rs.)",
      Metric: "Metric",
      Value: "Value",
      "Route-Wise Monthly Ledger Summary": "Route-Wise Monthly Ledger Summary",
      "View complete monthly breakdown of a specific route":
        "View complete monthly breakdown of a specific route",
      "Please select a route": "Please select a route",
      "Please select month and year": "Please select month and year",
      "View Summary": "View Summary",
      "Save as PDF": "Save as PDF",
      "Vehicle & Driver": "Vehicle & Driver",
      "Total Shops Linked": "Total Shops Linked",
      "Shop Breakdown": "Shop Breakdown",
      "Total KG": "Total KG",
      Remaining: "Remaining",
      "No data found for this month.": "No data found for this month.",
      "Route Totals:": "Route Totals:",
      "Total Shop KG": "Total Shop KG",
      "Total Factory KG": "Total Factory KG",

      // Users & Settings (NEW)
      "User Management": "User Management",
      "Manage Admin and restricted Staff accounts":
        "Manage Admin and restricted Staff accounts",
      "Add User": "Add User",
      "Edit Account": "Edit Account",
      "Create New Account": "Create New Account",
      "Full Name *": "Full Name *",
      "Email / Username *": "Email / Username *",
      Password: "Password",
      "(Leave empty to keep current)": "(Leave empty to keep current)",
      "Enter password": "Enter password",
      "Access Role": "Access Role",
      "Staff (Restricted Access)": "Staff (Restricted Access)",
      "Admin (Full Access)": "Admin (Full Access)",
      "Update Account": "Update Account",
      "Create Account": "Create Account",
      "Email / Username": "Email / Username",
      Role: "Role",
      "No users found.": "No users found.",
      "Delete User?": "Delete User?",
      "Are you sure you want to delete this user account? This action cannot be undone.":
        "Are you sure you want to delete this user account? This action cannot be undone.",
      "System Settings": "System Settings",
      "Manage your account, security, and application preferences":
        "Manage your account, security, and application preferences",
      "My Profile": "My Profile",
      "Security & Password": "Security & Password",
      "System Preferences": "System Preferences",
      "Personal Information": "Personal Information",
      "Full Name": "Full Name",
      "Email Address": "Email Address",
      "Save Changes": "Save Changes",
      "Change Password": "Change Password",
      "Set a new strong password for your account.":
        "Set a new strong password for your account.",
      "New Password": "New Password",
      "Confirm New Password": "Confirm New Password",
      "Update Password": "Update Password",
      "Updating...": "Updating...",
      "Currency Symbol": "Currency Symbol",
      "PKR (Rs)": "PKR (Rs)",
      "USD ($)": "USD ($)",
      Timezone: "Timezone",
      "Email Notifications": "Email Notifications",
      "Receive alerts for deleted records or large shortages.":
        "Receive alerts for deleted records or large shortages.",
      "Save Preferences": "Save Preferences",
    },
    ur: {
      // Menu & General
      Dashboard: "ڈیش بورڈ",
      Vehicles: "گاڑیاں",
      Routes: "روٹس",
      Shops: "دکانیں",
      "Daily Collection": "روزانہ کی وصولی",
      "Factory Weight": "فیکٹری کا وزن",
      "Shop Ledger": "دکان کا کھاتہ",
      "Route Ledger Summary": "روٹ کا کھاتہ",
      "Monthly Reports": "ماہانہ رپورٹس",
      Users: "صارفین",
      Settings: "سیٹنگز",
      Logout: "لاگ آؤٹ",
      "Keep Environment Clean": "بہتر کل کے لیے ماحول کو صاف رکھیں",
      "Management System": "مینجمنٹ سسٹم",
      Cancel: "منسوخ کریں",
      Save: "محفوظ کریں",
      "Saving...": "محفوظ ہو رہا ہے...",
      Status: "سٹیٹس",
      Active: "فعال",
      Inactive: "غیر فعال",
      Actions: "ایکشن",
      Edit: "ترمیم",
      Delete: "حذف کریں",
      "Yes, Delete": "ہاں، ڈیلیٹ کریں",
      Month: "مہینہ",
      Year: "سال",
      Date: "تاریخ",
      Action: "ایکشن",
      Name: "نام",

      // Dashboard Text
      "Welcome to Waste Management System": "ویسٹ مینجمنٹ سسٹم میں خوش آمدید",
      "Here is what's happening today, ": "آج کی تازہ ترین صورتحال، ",
      "Filter Overview": "فلٹر کا جائزہ",
      "Select Date": "تاریخ منتخب کریں",
      "Select Route": "روٹ منتخب کریں",
      "All Routes (Overall)": "تمام روٹس (مجموعی)",
      "Collection & Financials": "وصولی اور مالیات",
      "Total Shop Weight": "دکان کا کل وزن",
      "Total Factory Weight": "فیکٹری کا کل وزن",
      "Total Difference": "کل فرق",
      "Infrastructure Overview": "انفراسٹرکچر کا جائزہ",
      "Active Vehicles": "فعال گاڑیاں",
      "Active Routes": "فعال روٹس",
      "Registered Shops": "رجسٹرڈ دکانیں",

      // Daily Collection & Shop Ledger
      "Daily Shop Collection / Weight Entry":
        "روزانہ دکان کی وصولی / وزن کا اندراج",
      "Record daily poultry waste collection from shops":
        "دکانوں سے روزانہ پولٹری ویسٹ کی وصولی کا ریکارڈ",
      "-- Select Route --": "-- روٹ منتخب کریں --",
      "Assigned Vehicle": "مختص کردہ گاڑی",
      "No Vehicle!": "کوئی گاڑی نہیں!",
      "Loading shops...": "دکانیں لوڈ ہو رہی ہیں...",
      "No shops are assigned to this route. Please add shops first.":
        "اس روٹ میں کوئی دکان شامل نہیں ہے۔ براہ کرم پہلے دکانیں شامل کریں۔",
      "Shop Name": "دکان کا نام",
      "Rate / KG": "ریٹ / کلوگرام",
      "Weight Input": "وزن لکھیں",
      "Total Amount (Rs)": "کل رقم (روپے)",
      "Calculated:": "حساب:",
      "Route Total:": "روٹ کا کل:",
      "Rate:": "ریٹ:",
      "Enter Weight": "وزن لکھیں",
      "Total Amount:": "کل رقم:",
      "Route Total Weight:": "روٹ کا کل وزن:",
      "Total Payable:": "کل قابل ادائیگی:",
      "Saving Collection...": "وصولی محفوظ ہو رہی ہے...",
      "Save Daily Collection": "روزانہ کی وصولی محفوظ کریں",
      "Shop Ledger & Payments": "دکان کا کھاتہ اور ادائیگیاں",
      "Save PDF": "پی ڈی ایف محفوظ کریں",
      "Add Payment": "ادائیگی شامل کریں",
      "Select Shop": "دکان منتخب کریں",
      "-- Select Shop --": "-- دکان منتخب کریں --",
      "Edit Payment": "ادائیگی میں ترمیم کریں",
      "Record New Payment": "نئی ادائیگی درج کریں",
      "Amount (Rs.) *": "رقم (روپے) *",
      "Type *": "قسم *",
      "Debit (Paid to Shop)": "ڈیبٹ (دکان کو ادا کیا)",
      "Credit (Advance / Adjust)": "کریڈٹ (ایڈوانس / ایڈجسٹ)",
      Method: "طریقہ",
      Cash: "نقد",
      Check: "چیک",
      "Bank Transfer": "بینک ٹرانسفر",
      Other: "دیگر",
      "Notes / Check No.": "نوٹس / چیک نمبر",
      "Update Payment": "ادائیگی اپ ڈیٹ کریں",
      "Save Payment": "ادائیگی محفوظ کریں",
      "Total Collected": "کل وصولی",
      "Total Payable (Credit)": "کل قابل ادائیگی (کریڈٹ)",
      "Total Paid (Debit)": "کل ادا شدہ (ڈیبٹ)",
      "Remaining Balance": "بقیہ رقم",
      Description: "تفصیل",
      "Weight / Rate": "وزن / ریٹ",
      "Debit (Paid)": "ڈیبٹ (ادا شدہ)",
      "Credit (Payable)": "کریڈٹ (قابل ادائیگی)",
      Balance: "بیلنس",
      "No transactions found.": "کوئی لین دین نہیں ملا۔",
      "Waste Collection": "ویسٹ وصولی",
      Payment: "ادائیگی",
      "Note:": "نوٹ:",
      "Weight (KG)": "وزن (کلوگرام)",
      "Enter Weight (KG)": "وزن درج کریں (کلوگرام)",

      // Factory Weight
      "Factory Weight & Reports": "فیکٹری کا وزن اور رپورٹس",
      "Record New Factory Weight": "نیا فیکٹری وزن درج کریں",
      "No collection found for this date.": "اس تاریخ کی کوئی وصولی نہیں ملی۔",
      "Enter Factory Weight *": "فیکٹری کا وزن درج کریں *",
      Difference: "فرق",
      "Notes (Optional)": "نوٹس (اختیاری)",
      "Save Weight": "وزن محفوظ کریں",
      "Monthly Factory Report": "ماہانہ فیکٹری رپورٹ",
      "Excel File": "ایکسل فائل",
      Route: "روٹ",
      "Shop Wgt": "دکان کا وزن",
      "Factory Wgt": "فیکٹری کا وزن",
      Diff: "فرق",
      "Status / Notes": "سٹیٹس / نوٹس",
      "No factory records found for this month.":
        "اس مہینے کا کوئی فیکٹری ریکارڈ نہیں ملا۔",
      "Edit Factory Weight": "فیکٹری کے وزن میں ترمیم کریں",
      "Shop Weight:": "دکان کا وزن:",
      "New Factory Weight (KG)": "نیا فیکٹری وزن (کلوگرام)",
      Notes: "نوٹس",
      "Update Record": "ریکارڈ اپ ڈیٹ کریں",
      Extra: "اضافی",
      Shortage: "کمی",
      Balanced: "برابر",

      // Shops & Routes
      "Shops Management": "دکانوں کا انتظام",
      "Add Shop": "دکان شامل کریں",
      "Edit Shop": "دکان میں ترمیم کریں",
      "Add New Shop": "نئی دکان شامل کریں",
      "Shop Name *": "دکان کا نام *",
      "Owner Name *": "مالک کا نام *",
      "Contact (Optional)": "رابطہ نمبر (اختیاری)",
      "Assign Route *": "روٹ مختص کریں *",
      "Rate per KG (Rs.) *": "ریٹ فی کلوگرام (روپے) *",
      "Save Shop": "دکان محفوظ کریں",
      "Owner & Contact": "مالک اور رابطہ",
      "Assigned Route": "مختص کردہ روٹ",
      "Rate/KG": "ریٹ/کلوگرام",
      "No shops found. Please add a new shop.":
        "کوئی دکان نہیں ملی۔ براہ کرم نئی دکان شامل کریں۔",
      "Delete Shop?": "کیا دکان ڈیلیٹ کریں؟",
      "Are you sure you want to delete this shop? This action cannot be undone.":
        "کیا آپ واقعی اسے ڈیلیٹ کرنا چاہتے ہیں؟ یہ عمل واپس نہیں کیا جا سکتا۔",
      "Routes Management": "روٹس کا انتظام",
      "Add Route": "روٹ شامل کریں",
      "Edit Route": "روٹ میں ترمیم کریں",
      "Add New Route": "نیا روٹ شامل کریں",
      "Route Name *": "روٹ کا نام *",
      "Assign Vehicle": "گاڑی مختص کریں",
      "-- Select --": "-- منتخب کریں --",
      "Route Name": "روٹ کا نام",
      Vehicle: "گاڑی",
      Driver: "ڈرائیور",
      "Not Assigned": "مختص نہیں ہے",
      "Delete Route?": "کیا روٹ ڈیلیٹ کریں؟",
      "Serial Number": "سیریل نمبر",
      "Sr. No": "نمبر شمار",
      "All Routes": "تمام روٹس",
      "Serial updated!": "سیریل نمبر اپ ڈیٹ ہو گیا!",
      "Failed to update serial": "سیریل اپ ڈیٹ کرنے میں مسئلہ",

      // Vehicles
      "Vehicles Management": "گاڑیوں کا انتظام",
      "Manage all your transport vehicles":
        "اپنی تمام ٹرانسپورٹ گاڑیوں کا انتظام کریں",
      "Add Vehicle": "گاڑی شامل کریں",
      "Edit Vehicle": "گاڑی میں ترمیم کریں",
      "Add New Vehicle": "نئی گاڑی شامل کریں",
      "Vehicle Number *": "گاڑی کا نمبر *",
      "Vehicle Name/Type": "گاڑی کا نام/قسم",
      "Driver Name *": "ڈرائیور کا نام *",
      "Driver Contact *": "ڈرائیور کا نمبر *",
      "Under Maintenance": "مرمت جاری ہے",
      "Update Vehicle": "گاڑی اپ ڈیٹ کریں",
      "Save Vehicle": "گاڑی محفوظ کریں",
      "Vehicle No.": "گاڑی نمبر",
      "Name/Type": "نام / قسم",
      Contact: "رابطہ",
      "Delete Vehicle?": "کیا گاڑی ڈیلیٹ کریں؟",

      // Monthly Reports & Route Ledger
      "Monthly Business Report": "ماہانہ کاروباری رپورٹ",
      "Generate, view, and export overall business summaries":
        "مجموعی کاروباری خلاصہ بنائیں، دیکھیں اور ایکسپورٹ کریں",
      "Generating...": "رپورٹ بن رہی ہے...",
      "Generate Report": "رپورٹ بنائیں",
      "For ": "برائے ",
      Print: "پرنٹ کریں",
      PDF: "پی ڈی ایف",
      Excel: "ایکسل",
      "Total Routes": "کل روٹس",
      "Total Vehicles": "کل گاڑیاں",
      "Total Shops": "کل دکانیں",
      "Total Payable Amount": "کل قابل ادائیگی رقم",
      "Total Shop Weight (KG)": "دکان کا کل وزن (کلوگرام)",
      "Total Factory Weight (KG)": "فیکٹری کا کل وزن (کلوگرام)",
      "Total Difference (KG)": "کل فرق (کلوگرام)",
      "Total Payable Amount (Rs.)": "کل قابل ادائیگی رقم (روپے)",
      Metric: "پیمانہ",
      Value: "ویلیو",
      "Route-Wise Monthly Ledger Summary":
        "روٹ کے لحاظ سے ماہانہ کھاتہ کا خلاصہ",
      "View complete monthly breakdown of a specific route":
        "کسی خاص روٹ کی مکمل ماہانہ تفصیلات دیکھیں",
      "Please select a route": "براہ کرم کوئی روٹ منتخب کریں",
      "Please select month and year": "براہ کرم مہینہ اور سال منتخب کریں",
      "View Summary": "خلاصہ دیکھیں",
      "Save as PDF": "پی ڈی ایف محفوظ کریں",
      "Vehicle & Driver": "گاڑی اور ڈرائیور",
      "Total Shops Linked": "منسلک دکانوں کی کل تعداد",
      "Shop Breakdown": "دکانوں کی تفصیلات",
      "Total KG": "کل کلوگرام",
      Remaining: "بقیہ رقم",
      "No data found for this month.": "اس مہینے کا کوئی ڈیٹا نہیں ملا۔",
      "Route Totals:": "روٹ کا کل:",
      "Total Shop KG": "دکان کا کل کلوگرام",
      "Total Factory KG": "فیکٹری کا کل کلوگرام",

      // Users & Settings (NEW)
      "User Management": "صارفین کا انتظام",
      "Manage Admin and restricted Staff accounts":
        "ایڈمن اور محدود سٹاف اکاؤنٹس کا انتظام کریں",
      "Add User": "صارف شامل کریں",
      "Edit Account": "اکاؤنٹ میں ترمیم کریں",
      "Create New Account": "نیا اکاؤنٹ بنائیں",
      "Full Name *": "پورا نام *",
      "Email / Username *": "ای میل / یوزر نیم *",
      Password: "پاس ورڈ",
      "(Leave empty to keep current)": "(موجودہ رکھنے کے لیے خالی چھوڑ دیں)",
      "Enter password": "پاس ورڈ درج کریں",
      "Access Role": "رسائی کا کردار",
      "Staff (Restricted Access)": "سٹاف (محدود رسائی)",
      "Admin (Full Access)": "ایڈمن (مکمل رسائی)",
      "Update Account": "اکاؤنٹ اپ ڈیٹ کریں",
      "Create Account": "اکاؤنٹ بنائیں",
      "Email / Username": "ای میل / یوزر نیم",
      Role: "کردار",
      "No users found.": "کوئی صارف نہیں ملا۔",
      "Delete User?": "کیا صارف کو ڈیلیٹ کریں؟",
      "Are you sure you want to delete this user account? This action cannot be undone.":
        "کیا آپ واقعی اس صارف کا اکاؤنٹ ڈیلیٹ کرنا چاہتے ہیں؟ یہ عمل واپس نہیں کیا جا سکتا۔",
      "System Settings": "سسٹم سیٹنگز",
      "Manage your account, security, and application preferences":
        "اپنے اکاؤنٹ، سیکیورٹی اور ایپلیکیشن کی ترجیحات کا انتظام کریں",
      "My Profile": "میری پروفائل",
      "Security & Password": "سیکیورٹی اور پاس ورڈ",
      "System Preferences": "سسٹم کی ترجیحات",
      "Personal Information": "ذاتی معلومات",
      "Full Name": "پورا نام",
      "Email Address": "ای میل ایڈریس",
      "Save Changes": "تبدیلیاں محفوظ کریں",
      "Change Password": "پاس ورڈ تبدیل کریں",
      "Set a new strong password for your account.":
        "اپنے اکاؤنٹ کے لیے ایک نیا مضبوط پاس ورڈ سیٹ کریں۔",
      "New Password": "نیا پاس ورڈ",
      "Confirm New Password": "نئے پاس ورڈ کی تصدیق کریں",
      "Update Password": "پاس ورڈ اپ ڈیٹ کریں",
      "Updating...": "اپ ڈیٹ ہو رہا ہے...",
      "Currency Symbol": "کرنسی کی علامت",
      "PKR (Rs)": "پاکستانی روپیہ (Rs)",
      "USD ($)": "امریکی ڈالر ($)",
      Timezone: "ٹائم زون",
      "Email Notifications": "ای میل نوٹیفکیشنز",
      "Receive alerts for deleted records or large shortages.":
        "ڈیلیٹ کیے گئے ریکارڈز یا بڑی کمی پر الرٹس وصول کریں۔",
      "Save Preferences": "ترجیحات محفوظ کریں",
    },
  };

  const t = (word) => {
    return translations[language]?.[word] || word;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
